use radeis_sc2sbom::models::DependencySource;
use radeis_sc2sbom::parsers::cargo::{parse_cargo_lock_with_relationships, parse_cargo_toml};
use std::io::Write;
use tempfile::NamedTempFile;

#[test]
fn test_parse_cargo_toml_simple_versions() {
    let content = r#"
[package]
name = "test-project"
version = "0.1.0"

[dependencies]
serde = "1.0"
tokio = "1.20.0"
anyhow = "1.0.57"
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_cargo_toml(temp_file.path()).unwrap();

    assert_eq!(deps.len(), 3);

    let serde = deps.iter().find(|d| d.name == "serde").unwrap();
    assert_eq!(serde.version, "1.0");
    assert_eq!(serde.ecosystem, "cargo");

    let tokio = deps.iter().find(|d| d.name == "tokio").unwrap();
    assert_eq!(tokio.version, "1.20.0");
}

#[test]
fn test_parse_cargo_toml_table_versions() {
    let content = r#"
[package]
name = "test-project"
version = "0.1.0"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_cargo_toml(temp_file.path()).unwrap();

    assert_eq!(deps.len(), 2);

    let clap = deps.iter().find(|d| d.name == "clap").unwrap();
    assert_eq!(clap.version, "4.5");
    assert_eq!(clap.ecosystem, "cargo");
}

#[test]
fn test_parse_cargo_lock() {
    let content = r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "anyhow"
version = "1.0.75"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "a4668cab20f66d8d020e1fbc0ebe47217433c1b6c8f2040faf858554e394ace6"

[[package]]
name = "serde"
version = "1.0.188"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cf9e0fcba69a370eed61bcf2b728575f726b50b55cba78064753d708ddc7549e"
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let data = parse_cargo_lock_with_relationships(temp_file.path()).unwrap();
    let deps = data.dependencies;

    assert_eq!(deps.len(), 2);

    let anyhow = deps.iter().find(|d| d.name == "anyhow").unwrap();
    assert_eq!(anyhow.version, "1.0.75");
    assert_eq!(anyhow.ecosystem, "cargo");
    assert!(matches!(anyhow.source, DependencySource::LockFile));

    let serde = deps.iter().find(|d| d.name == "serde").unwrap();
    assert_eq!(serde.version, "1.0.188");
}

#[test]
fn test_parse_cargo_lock_with_relationships() {
    let content = r#"# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "parent"
version = "1.0.0"
dependencies = [
 "child1",
 "child2",
]

[[package]]
name = "child1"
version = "0.5.0"

[[package]]
name = "child2"
version = "0.3.0"
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let data = parse_cargo_lock_with_relationships(temp_file.path()).unwrap();

    assert_eq!(data.dependencies.len(), 3);
    assert!(!data.relationships.is_empty());

    // Verify relationship exists from parent to children
    let parent_rel = data
        .relationships
        .iter()
        .find(|r| r.parent_id.contains("parent"))
        .unwrap();
    assert!(parent_rel.child_names.len() >= 1);
}

// Source tracking tests

#[test]
fn test_cargo_source_tracking_toml() {
    let content = r#"
[package]
name = "test-project"
version = "0.1.0"

[dependencies]
serde = "1.0"
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_cargo_toml(temp_file.path()).unwrap();

    assert_eq!(deps.len(), 1);
    let source = deps[0].source_file.as_ref().unwrap();
    assert!(source.starts_with("Identified by the rust/cargo extractor from"));
    assert!(source.contains(temp_file.path().to_str().unwrap()));
}

#[test]
fn test_cargo_source_tracking_lock() {
    let content = r#"# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "serde"
version = "1.0.0"
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let data = parse_cargo_lock_with_relationships(temp_file.path()).unwrap();

    assert!(!data.dependencies.is_empty());
    let source = data.dependencies[0].source_file.as_ref().unwrap();
    assert!(source.starts_with("Identified by the rust/cargolock extractor from"));
    assert!(source.contains(temp_file.path().to_str().unwrap()));
}
