use radeis_sc2sbom::models::DependencySource;
use radeis_sc2sbom::parsers::python::{
    parse_pipfile, parse_pipfile_lock_with_relationships, parse_poetry_lock_with_relationships,
    parse_pyproject_toml, parse_requirements_txt, parse_setup_py,
};
use std::io::Write;
use tempfile::NamedTempFile;

#[test]
fn test_parse_requirements_txt_with_versions() {
    let content = r#"Django==3.2.0
requests==2.26.0
numpy==1.21.0
# This is a comment
pytest==6.2.4
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_requirements_txt(temp_file.path()).unwrap();

    assert_eq!(deps.len(), 4);

    let django = deps.iter().find(|d| d.name == "Django").unwrap();
    assert_eq!(django.version, "3.2.0");
    assert_eq!(django.ecosystem, "pip");

    let requests = deps.iter().find(|d| d.name == "requests").unwrap();
    assert_eq!(requests.version, "2.26.0");
}

#[test]
fn test_parse_requirements_txt_without_versions() {
    let content = r#"Django
requests
numpy
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_requirements_txt(temp_file.path()).unwrap();

    assert_eq!(deps.len(), 3);

    for dep in &deps {
        assert_eq!(dep.version, "unspecified");
        assert_eq!(dep.ecosystem, "pip");
    }
}

#[test]
fn test_parse_requirements_txt_with_comments() {
    let content = r#"
# Main dependencies
Django==3.2.0

# Testing
pytest==6.2.4

"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_requirements_txt(temp_file.path()).unwrap();

    assert_eq!(deps.len(), 2);
}

#[test]
fn test_parse_requirements_txt_with_operators() {
    // v1.0.0: Non-exact version specs now return "unspecified" to avoid misleading version info
    // Only exact pins (== or =) are extracted as actual versions
    let content = r#"reportlab>=4.0.0
python-docx==1.1.0
matplotlib~=3.7.0
pillow<=10.0.0
pandas>2.0.0
numpy<1.24.0
requests!=2.28.0
flask>=2.0,<3.0
Django[bcrypt]==3.2.0
# Comment line
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_requirements_txt(temp_file.path()).unwrap();

    assert_eq!(deps.len(), 9);

    // Non-exact specs should return "unspecified"
    let reportlab = deps.iter().find(|d| d.name == "reportlab").unwrap();
    assert_eq!(reportlab.version, "unspecified");
    assert_eq!(reportlab.ecosystem, "pip");

    // Exact pin with == should extract version
    let python_docx = deps.iter().find(|d| d.name == "python-docx").unwrap();
    assert_eq!(python_docx.version, "1.1.0");

    // Django with extra and exact pin
    let django = deps.iter().find(|d| d.name == "Django[bcrypt]").unwrap();
    assert_eq!(django.version, "3.2.0");
}

#[test]
fn test_parse_poetry_lock() {
    let content = r#"# This file is automatically @generated by Poetry 1.6.1 and should not be changed by hand.

[[package]]
name = "certifi"
version = "2023.7.22"
description = "Python package for providing Mozilla's CA Bundle."
optional = false
python-versions = ">=3.6"
category = "main"

[[package]]
name = "pytest"
version = "7.4.2"
description = "pytest: simple powerful testing with Python"
optional = false
python-versions = ">=3.7"
category = "dev"
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let data = parse_poetry_lock_with_relationships(temp_file.path(), false).unwrap();
    let deps = data.dependencies;

    assert_eq!(deps.len(), 2);

    let certifi = deps.iter().find(|d| d.name == "certifi").unwrap();
    assert_eq!(certifi.version, "2023.7.22");
    assert_eq!(certifi.ecosystem, "pip");
    assert!(!certifi.is_dev);
    assert!(matches!(certifi.source, DependencySource::LockFile));

    let pytest = deps.iter().find(|d| d.name == "pytest").unwrap();
    assert_eq!(pytest.version, "7.4.2");
    assert!(pytest.is_dev);
}

#[test]
fn test_parse_poetry_lock_with_relationships() {
    let content = r#"
[[package]]
name = "requests"
version = "2.28.2"
category = "main"

[package.dependencies]
certifi = ">=2017.4.17"
charset-normalizer = ">=2,<4"
idna = ">=2.5,<4"
urllib3 = ">=1.21.1,<1.27"

[[package]]
name = "certifi"
version = "2023.7.22"
category = "main"

[[package]]
name = "charset-normalizer"
version = "3.3.0"
category = "main"

[[package]]
name = "idna"
version = "3.4"
category = "main"

[[package]]
name = "urllib3"
version = "1.26.18"
category = "main"

[[package]]
name = "pytest"
version = "7.4.0"
category = "dev"

[package.dependencies]
pluggy = ">=0.12,<2.0"

[[package]]
name = "pluggy"
version = "1.3.0"
category = "dev"
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let data = parse_poetry_lock_with_relationships(temp_file.path(), false).unwrap();

    // Verify all 7 packages were parsed
    assert_eq!(data.dependencies.len(), 7);

    // Verify packages have correct metadata
    let requests = data
        .dependencies
        .iter()
        .find(|d| d.name == "requests")
        .unwrap();
    assert_eq!(requests.version, "2.28.2");
    assert_eq!(requests.ecosystem, "pip");
    assert_eq!(requests.source, DependencySource::LockFile);
    assert!(!requests.is_dev);

    // Verify dev dependency
    let pytest = data
        .dependencies
        .iter()
        .find(|d| d.name == "pytest")
        .unwrap();
    assert!(pytest.is_dev);

    // Verify relationships were extracted
    assert_eq!(data.relationships.len(), 2);

    // Verify requests's relationships
    let requests_rel = data
        .relationships
        .iter()
        .find(|r| r.parent_id == "requests@2.28.2")
        .unwrap();
    assert_eq!(requests_rel.child_names.len(), 4);
    assert!(requests_rel.child_names.contains(&"certifi".to_string()));
    assert!(requests_rel
        .child_names
        .contains(&"charset-normalizer".to_string()));
    assert!(requests_rel.child_names.contains(&"idna".to_string()));
    assert!(requests_rel.child_names.contains(&"urllib3".to_string()));

    // Verify pytest's relationships
    let pytest_rel = data
        .relationships
        .iter()
        .find(|r| r.parent_id == "pytest@7.4.0")
        .unwrap();
    assert_eq!(pytest_rel.child_names.len(), 1);
    assert_eq!(pytest_rel.child_names[0], "pluggy");
}

#[test]
fn test_parse_setup_py_basic() {
    let content = r#"from setuptools import setup

setup(
    name='ros2action',
    version='0.40.4',
    install_requires=['ros2cli', 'rclpy>=2.0'],
    extras_require={'test': ['pytest>=6.0']},
)
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let (version, deps) = parse_setup_py(temp_file.path()).unwrap();

    assert_eq!(version, Some("0.40.4".to_string()));
    assert_eq!(deps.len(), 3);

    let rclpy = deps.iter().find(|d| d.name == "rclpy").unwrap();
    assert_eq!(rclpy.version, ">=2.0");
    assert_eq!(rclpy.ecosystem, "pip");
    assert_eq!(rclpy.is_dev, false);

    let pytest = deps.iter().find(|d| d.name == "pytest").unwrap();
    assert_eq!(pytest.version, ">=6.0");
    assert_eq!(pytest.is_dev, true);
}

// Source tracking tests

#[test]
fn test_python_source_tracking_requirements() {
    let content = "requests==2.28.0\ndjango==3.2.0";

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_requirements_txt(temp_file.path()).unwrap();

    assert!(!deps.is_empty());
    let source = deps[0].source_file.as_ref().unwrap();
    assert!(source.starts_with("Identified by the python/requirements extractor from"));
    assert!(source.contains(temp_file.path().to_str().unwrap()));
}

#[test]
fn test_python_source_tracking_setup_py() {
    let content = r#"
from setuptools import setup

setup(
    name='test-package',
    version='1.0.0',
    install_requires=[
        'requests>=2.20.0',
        'flask==1.1.2',
    ],
)
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let (_, deps) = parse_setup_py(temp_file.path()).unwrap();

    assert!(!deps.is_empty());
    let source = deps[0].source_file.as_ref().unwrap();
    assert!(source.starts_with("Identified by the python/setuppy extractor from"));
    assert!(source.contains(temp_file.path().to_str().unwrap()));
}

#[test]
fn test_python_source_tracking_poetry() {
    let content = r#"[[package]]
name = "requests"
version = "2.28.0"
category = "main"
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let data = parse_poetry_lock_with_relationships(temp_file.path(), false).unwrap();

    assert!(!data.dependencies.is_empty());
    let source = data.dependencies[0].source_file.as_ref().unwrap();
    assert!(source.starts_with("Identified by the python/poetry extractor from"));
    assert!(source.contains(temp_file.path().to_str().unwrap()));
}

// ============================================================================
// Pipfile.lock Tests (v0.9.3)
// ============================================================================

#[test]
fn test_parse_pipfile_lock_basic() {
    let content = r#"{
    "_meta": {
        "hash": {
            "sha256": "abc123"
        },
        "pipfile-spec": 6
    },
    "default": {
        "azure-identity": {
            "hashes": [
                "sha256:7cca6ab79b62bb6a56f831d5bd6b0188f0a11d528e55a40c3d1e17ad031f00cb",
                "sha256:def456"
            ],
            "index": "pypi",
            "version": "==1.12.0"
        },
        "requests": {
            "hashes": [
                "sha256:abc789"
            ],
            "version": "==2.31.0"
        }
    },
    "develop": {}
}"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let data = parse_pipfile_lock_with_relationships(temp_file.path(), false).unwrap();
    let deps = data.dependencies;

    assert_eq!(deps.len(), 2);

    let azure_identity = deps.iter().find(|d| d.name == "azure-identity").unwrap();
    assert_eq!(azure_identity.version, "1.12.0");
    assert_eq!(azure_identity.ecosystem, "pip");
    assert_eq!(azure_identity.source, DependencySource::LockFile);
    assert!(!azure_identity.is_dev);
    assert!(azure_identity.is_direct); // Has index field
    assert_eq!(
        azure_identity.checksum_sha256,
        Some("7cca6ab79b62bb6a56f831d5bd6b0188f0a11d528e55a40c3d1e17ad031f00cb".to_string())
    );

    let requests = deps.iter().find(|d| d.name == "requests").unwrap();
    assert_eq!(requests.version, "2.31.0");
    assert!(!requests.is_direct); // No index field = transitive
    assert_eq!(requests.checksum_sha256, Some("abc789".to_string()));
}

#[test]
fn test_parse_pipfile_lock_with_develop() {
    let content = r#"{
    "_meta": {},
    "default": {
        "requests": {
            "hashes": ["sha256:abc123"],
            "index": "pypi",
            "version": "==2.31.0"
        }
    },
    "develop": {
        "pytest": {
            "hashes": ["sha256:def456"],
            "index": "pypi",
            "version": "==7.4.0"
        },
        "black": {
            "hashes": ["sha256:ghi789"],
            "version": "==23.0.0"
        }
    }
}"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let data = parse_pipfile_lock_with_relationships(temp_file.path(), false).unwrap();
    let deps = data.dependencies;

    assert_eq!(deps.len(), 3);

    // Verify production dependency
    let requests = deps.iter().find(|d| d.name == "requests").unwrap();
    assert!(!requests.is_dev);
    assert!(requests.is_direct);

    // Verify development dependencies
    let pytest = deps.iter().find(|d| d.name == "pytest").unwrap();
    assert!(pytest.is_dev);
    assert!(pytest.is_direct);

    let black = deps.iter().find(|d| d.name == "black").unwrap();
    assert!(black.is_dev);
    assert!(!black.is_direct); // No index field
}

#[test]
fn test_parse_pipfile_lock_version_trimming() {
    let content = r#"{
    "_meta": {},
    "default": {
        "package1": {
            "hashes": [],
            "version": "==1.2.3"
        },
        "package2": {
            "hashes": [],
            "version": "==2.0.0"
        }
    },
    "develop": {}
}"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let data = parse_pipfile_lock_with_relationships(temp_file.path(), false).unwrap();
    let deps = data.dependencies;

    assert_eq!(deps.len(), 2);

    // Verify version "==" prefix is stripped
    let pkg1 = deps.iter().find(|d| d.name == "package1").unwrap();
    assert_eq!(pkg1.version, "1.2.3");

    let pkg2 = deps.iter().find(|d| d.name == "package2").unwrap();
    assert_eq!(pkg2.version, "2.0.0");
}

#[test]
fn test_parse_pipfile_lock_no_relationships() {
    let content = r#"{
    "_meta": {},
    "default": {
        "requests": {
            "hashes": [],
            "version": "==2.31.0"
        }
    },
    "develop": {}
}"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let data = parse_pipfile_lock_with_relationships(temp_file.path(), false).unwrap();

    // Pipfile.lock doesn't encode dependency relationships
    assert_eq!(data.relationships.len(), 0);
}

#[test]
fn test_parse_pipfile_lock_source_tracking() {
    let content = r#"{
    "_meta": {},
    "default": {
        "requests": {
            "hashes": [],
            "version": "==2.31.0"
        }
    },
    "develop": {}
}"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let data = parse_pipfile_lock_with_relationships(temp_file.path(), false).unwrap();

    assert!(!data.dependencies.is_empty());
    let source = data.dependencies[0].source_file.as_ref().unwrap();
    assert!(source.starts_with("Identified by the python/pipfilelock extractor from"));
    assert!(source.contains(temp_file.path().to_str().unwrap()));
}

// ============================================================================
// Pipfile Tests (v0.9.3)
// ============================================================================

#[test]
fn test_parse_pipfile_basic() {
    let content = r#"
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
jinja2 = "*"
requests = ">=2.28.0"
azure-identity = "==1.12.0"

[dev-packages]
pytest = "*"
black = ">=23.0"

[requires]
python_version = "3.8"
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_pipfile(temp_file.path(), false).unwrap();

    assert_eq!(deps.len(), 5);

    // Verify production dependencies
    let jinja2 = deps.iter().find(|d| d.name == "jinja2").unwrap();
    assert_eq!(jinja2.version, "unspecified");
    assert_eq!(jinja2.ecosystem, "pip");
    assert_eq!(jinja2.source, DependencySource::Manifest);
    assert!(!jinja2.is_dev);
    assert!(jinja2.is_direct);

    let requests = deps.iter().find(|d| d.name == "requests").unwrap();
    assert_eq!(requests.version, ">=2.28.0");
    assert!(!requests.is_dev);

    let azure = deps.iter().find(|d| d.name == "azure-identity").unwrap();
    assert_eq!(azure.version, "1.12.0"); // "==" should be stripped

    // Verify development dependencies
    let pytest = deps.iter().find(|d| d.name == "pytest").unwrap();
    assert!(pytest.is_dev);
    assert_eq!(pytest.version, "unspecified");

    let black = deps.iter().find(|d| d.name == "black").unwrap();
    assert!(black.is_dev);
    assert_eq!(black.version, ">=23.0");
}

#[test]
fn test_parse_pipfile_version_specs() {
    let content = r#"
[packages]
package1 = "*"
package2 = ">=1.0"
package3 = "==2.0.0"
package4 = "~=1.2.0"
package5 = {version = ">=3.0", extras = ["dev"]}
package6 = {version = "==1.5.0"}
package7 = {version = "*"}

[dev-packages]
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_pipfile(temp_file.path(), false).unwrap();

    assert_eq!(deps.len(), 7);

    let pkg1 = deps.iter().find(|d| d.name == "package1").unwrap();
    assert_eq!(pkg1.version, "unspecified");

    let pkg2 = deps.iter().find(|d| d.name == "package2").unwrap();
    assert_eq!(pkg2.version, ">=1.0");

    let pkg3 = deps.iter().find(|d| d.name == "package3").unwrap();
    assert_eq!(pkg3.version, "2.0.0"); // "==" stripped

    let pkg4 = deps.iter().find(|d| d.name == "package4").unwrap();
    assert_eq!(pkg4.version, "~=1.2.0");

    let pkg5 = deps.iter().find(|d| d.name == "package5").unwrap();
    assert_eq!(pkg5.version, ">=3.0");

    let pkg6 = deps.iter().find(|d| d.name == "package6").unwrap();
    assert_eq!(pkg6.version, "1.5.0"); // "==" stripped from table spec

    let pkg7 = deps.iter().find(|d| d.name == "package7").unwrap();
    assert_eq!(pkg7.version, "unspecified"); // "*" in table spec normalized to "unspecified"
}

#[test]
fn test_parse_pipfile_source_tracking() {
    let content = r#"
[packages]
requests = "*"

[dev-packages]
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_pipfile(temp_file.path(), false).unwrap();

    assert!(!deps.is_empty());
    let source = deps[0].source_file.as_ref().unwrap();
    assert!(source.starts_with("Identified by the python/pipfile extractor from"));
    assert!(source.contains(temp_file.path().to_str().unwrap()));
}

// ============================================================================
// pyproject.toml Tests (v0.9.3)
// ============================================================================

#[test]
fn test_parse_pyproject_toml_pep621() {
    let content = r#"
[project]
name = "example-package"
version = "1.0.0"
dependencies = [
    "requests>=2.28.0",
    "click>=8.0.0",
    "pydantic[email]>=2.0.0"
]

[project.optional-dependencies]
dev = ["pytest>=7.0", "black>=23.0"]
test = ["coverage>=6.0"]
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_pyproject_toml(temp_file.path(), false).unwrap();

    assert_eq!(deps.len(), 6);

    // Verify production dependencies
    let requests = deps.iter().find(|d| d.name == "requests").unwrap();
    assert_eq!(requests.version, ">=2.28.0");
    assert_eq!(requests.ecosystem, "pip");
    assert_eq!(requests.source, DependencySource::Manifest);
    assert!(!requests.is_dev);

    // Verify extras are preserved
    let pydantic = deps.iter().find(|d| d.name == "pydantic[email]").unwrap();
    assert_eq!(pydantic.version, ">=2.0.0");

    // Verify dev dependencies
    let pytest = deps.iter().find(|d| d.name == "pytest").unwrap();
    assert!(pytest.is_dev);
    assert_eq!(pytest.version, ">=7.0");

    let black = deps.iter().find(|d| d.name == "black").unwrap();
    assert!(black.is_dev);

    let coverage = deps.iter().find(|d| d.name == "coverage").unwrap();
    assert!(coverage.is_dev); // "test" group is treated as dev
}

#[test]
fn test_parse_pyproject_toml_poetry() {
    let content = r#"
[tool.poetry]
name = "example-package"
version = "1.0.0"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.0"
click = "~=8.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
black = "*"
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_pyproject_toml(temp_file.path(), false).unwrap();

    // Should have 4 deps (excluding python itself)
    assert_eq!(deps.len(), 4);

    let requests = deps.iter().find(|d| d.name == "requests").unwrap();
    assert_eq!(requests.version, "^2.28.0");
    assert!(!requests.is_dev);

    let click = deps.iter().find(|d| d.name == "click").unwrap();
    assert_eq!(click.version, "~=8.0");

    let pytest = deps.iter().find(|d| d.name == "pytest").unwrap();
    assert!(pytest.is_dev);

    let black = deps.iter().find(|d| d.name == "black").unwrap();
    assert!(black.is_dev);
    assert_eq!(black.version, "unspecified");
}

#[test]
fn test_parse_pyproject_toml_pdm() {
    let content = r#"
[tool.pdm]
dependencies = [
    "requests>=2.28.0",
    "click>=8.0.0"
]

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.0",
    "coverage>=6.0"
]
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_pyproject_toml(temp_file.path(), false).unwrap();

    assert_eq!(deps.len(), 4);

    let requests = deps.iter().find(|d| d.name == "requests").unwrap();
    assert_eq!(requests.version, ">=2.28.0");
    assert!(!requests.is_dev);

    let pytest = deps.iter().find(|d| d.name == "pytest").unwrap();
    assert!(pytest.is_dev);
}

#[test]
fn test_parse_pyproject_toml_format_priority() {
    // Test that Poetry format takes priority when multiple formats exist
    let content = r#"
[project]
dependencies = ["pep621-only>=1.0"]

[tool.poetry.dependencies]
python = "^3.8"
poetry-only = "^2.0"

[tool.pdm]
dependencies = ["pdm-only>=3.0"]
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_pyproject_toml(temp_file.path(), false).unwrap();

    // Should only parse Poetry format (priority: Poetry > PEP621 > PDM)
    assert_eq!(deps.len(), 1);

    let poetry_dep = deps.iter().find(|d| d.name == "poetry-only").unwrap();
    assert_eq!(poetry_dep.version, "^2.0");

    // Should NOT include pep621-only or pdm-only (lower priority)
    assert!(deps.iter().find(|d| d.name == "pep621-only").is_none());
    assert!(deps.iter().find(|d| d.name == "pdm-only").is_none());
}

#[test]
fn test_parse_pyproject_toml_pep621_priority_over_pdm() {
    // Test that PEP621 takes priority over PDM when Poetry is absent
    let content = r#"
[project]
dependencies = ["pep621-package>=1.0"]

[tool.pdm]
dependencies = ["pdm-package>=2.0"]
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_pyproject_toml(temp_file.path(), false).unwrap();

    // Should only parse PEP621 format (Poetry absent, PEP621 > PDM)
    assert_eq!(deps.len(), 1);

    let pep621_dep = deps.iter().find(|d| d.name == "pep621-package").unwrap();
    assert_eq!(pep621_dep.version, ">=1.0");

    // Should NOT include pdm-package (lower priority)
    assert!(deps.iter().find(|d| d.name == "pdm-package").is_none());
}

#[test]
fn test_parse_pyproject_toml_source_tracking() {
    let content = r#"
[project]
dependencies = ["requests>=2.28.0"]
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_pyproject_toml(temp_file.path(), false).unwrap();

    assert!(!deps.is_empty());
    let source = deps[0].source_file.as_ref().unwrap();
    assert!(source.starts_with("Identified by the python/pyproject extractor from"));
    assert!(source.contains(temp_file.path().to_str().unwrap()));
}

// ============================================================================
// Extras Handling Tests (v0.9.3)
// ============================================================================

#[test]
fn test_extras_handling_in_pyproject_toml() {
    let content = r#"
[project]
dependencies = [
    "pydantic[email]>=2.0.0",
    "Django[bcrypt,argon2]>=4.0",
    "celery[redis]~=5.2"
]
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_pyproject_toml(temp_file.path(), false).unwrap();

    assert_eq!(deps.len(), 3);

    let pydantic = deps.iter().find(|d| d.name == "pydantic[email]").unwrap();
    assert_eq!(pydantic.version, ">=2.0.0");

    let django = deps
        .iter()
        .find(|d| d.name == "Django[bcrypt,argon2]")
        .unwrap();
    assert_eq!(django.version, ">=4.0");

    let celery = deps.iter().find(|d| d.name == "celery[redis]").unwrap();
    assert_eq!(celery.version, "~=5.2");
}

#[test]
fn test_extras_handling_edge_cases() {
    let content = r#"
[project]
dependencies = [
    "package-no-extras>=1.0",
    "package[extra1]>=2.0",
    "package[extra1,extra2,extra3]>=3.0"
]
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let deps = parse_pyproject_toml(temp_file.path(), false).unwrap();

    assert_eq!(deps.len(), 3);

    let no_extras = deps.iter().find(|d| d.name == "package-no-extras").unwrap();
    assert_eq!(no_extras.version, ">=1.0");

    let one_extra = deps.iter().find(|d| d.name == "package[extra1]").unwrap();
    assert_eq!(one_extra.version, ">=2.0");

    let multi_extras = deps
        .iter()
        .find(|d| d.name == "package[extra1,extra2,extra3]")
        .unwrap();
    assert_eq!(multi_extras.version, ">=3.0");
}

// ============================================================================
// Checksum Extraction Tests (v0.9.3)
// ============================================================================

#[test]
fn test_checksum_extraction_pipfile_lock() {
    let content = r#"{
    "_meta": {},
    "default": {
        "package-with-hashes": {
            "hashes": [
                "sha256:abc123def456",
                "sha256:ghi789jkl012"
            ],
            "version": "==1.0.0"
        },
        "package-no-hashes": {
            "hashes": [],
            "version": "==2.0.0"
        }
    },
    "develop": {}
}"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let data = parse_pipfile_lock_with_relationships(temp_file.path(), false).unwrap();
    let deps = data.dependencies;

    let with_hash = deps
        .iter()
        .find(|d| d.name == "package-with-hashes")
        .unwrap();
    assert_eq!(with_hash.checksum_sha256, Some("abc123def456".to_string()));

    let no_hash = deps.iter().find(|d| d.name == "package-no-hashes").unwrap();
    assert_eq!(no_hash.checksum_sha256, None);
}

#[test]
fn test_checksum_extraction_poetry_lock() {
    let content = r#"
[[package]]
name = "package-with-checksum"
version = "1.0.0"
category = "main"

[[package.files]]
file = "package_with_checksum-1.0.0-py3-none-any.whl"
hash = "sha256:abc123def456"

[[package]]
name = "package-no-checksum"
version = "2.0.0"
category = "main"
"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let data = parse_poetry_lock_with_relationships(temp_file.path(), false).unwrap();
    let deps = data.dependencies;

    let with_hash = deps
        .iter()
        .find(|d| d.name == "package-with-checksum")
        .unwrap();
    assert_eq!(with_hash.checksum_sha256, Some("abc123def456".to_string()));

    let no_hash = deps
        .iter()
        .find(|d| d.name == "package-no-checksum")
        .unwrap();
    assert_eq!(no_hash.checksum_sha256, None);
}

#[test]
fn test_checksum_extraction_multiple_hashes() {
    // Test that first SHA256 hash is extracted when multiple present
    let content = r#"{
    "_meta": {},
    "default": {
        "package": {
            "hashes": [
                "sha256:first_hash",
                "sha256:second_hash",
                "sha256:third_hash"
            ],
            "version": "==1.0.0"
        }
    },
    "develop": {}
}"#;

    let mut temp_file = NamedTempFile::new().unwrap();
    temp_file.write_all(content.as_bytes()).unwrap();
    temp_file.flush().unwrap();

    let data = parse_pipfile_lock_with_relationships(temp_file.path(), false).unwrap();
    let deps = data.dependencies;

    let pkg = deps.iter().find(|d| d.name == "package").unwrap();
    assert_eq!(pkg.checksum_sha256, Some("first_hash".to_string()));
}
